import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.SIDEBAR.content_mang",
    moduleName: "",
    iconType: "",
    icon: "",
    icon_active: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules
  {
    path: "/admin/dashboard/main",
    title: "MENUITEMS.SIDEBAR.dashboard",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/dashboard.png",
    icon_active: "assets/images/sidebar/dashboard_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

  ,{
    path: "/admin/dashboard/content-module",
    title: "MENUITEMS.SIDEBAR.contents",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/folder.png",
    icon_active: "assets/images/sidebar/folder_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/playlist",
    title: "MENUITEMS.SIDEBAR.playlists",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/playlist.png",
    icon_active: "assets/images/sidebar/playlist_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  ,
  {
    path: "/admin/dashboard/schedules",
    title: "MENUITEMS.SIDEBAR.scheduling",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/schedule.png",
    icon_active: "assets/images/sidebar/schedule_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  ,
  {
    path: "/admin/dashboard/screens",
    title: "Screens",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/devices.png",
    icon_active: "assets/images/sidebar/devices_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "",
    title: "MENUITEMS.SIDEBAR.personalization",
    moduleName: "",
    iconType: "",
    icon: "assets/images/sidebar/location.png",
    icon_active: "assets/images/sidebar/location_s.png",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules
  {
    path: "/admin/dashboard/main5",
    title: "MENUITEMS.SIDEBAR.upselling",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/dollar.png",
    icon_active: "assets/images/sidebar/dollar_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

  ,{
    path: "/admin/dashboard/main23",
    title: "MENUITEMS.SIDEBAR.customer_experince",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/people.png",
    icon_active: "assets/images/sidebar/people_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
 ];


 export const Setting_ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "Settings",
    moduleName: "",
    iconType: "",
    icon: "assets/images/sidebar/location.png",
    icon_active: "assets/images/sidebar/location_s.png",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules
  {
    path: "/usermanagement/location",
    title: "MENUITEMS.SIDEBAR.location",
    moduleName: "dashboard",
    iconType: "",
    class: "",
    icon: "assets/images/sidebar/location.png",
    icon_active: "assets/images/sidebar/location_s.png",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

  ,{
    path: "/usermanagement/users",
    title: "MENUITEMS.SIDEBAR.users",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/user.png",
    icon_active: "assets/images/sidebar/user_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "/admin/dashboard/main1rr",
    title: "MENUITEMS.SIDEBAR.devices",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/devices.png",
    icon_active: "assets/images/sidebar/devices_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  ,
  {
    path: "/admin/dashboard/main1",
    title: "MENUITEMS.SIDEBAR.order_devices",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/checkout.png",
    icon_active: "assets/images/sidebar/checkout_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },
  {
    path: "n/dashboard/",
    title: "MENUITEMS.SIDEBAR.subscription",
    moduleName: "dashboard",
    iconType: "material-icons-two-tone",
    icon: "assets/images/sidebar/renew.png",
    icon_active: "assets/images/sidebar/renew_s.png",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [],
  },

 ];
